[helpers]

[default]
depends = [
]

[default.files]
gitui = ""
helix = "~/.config/helix"
pwsh  = ""
yazi  = { target = "~/.config/yazi", type = "symbolic", recurse = false }

[default.variables]

[settings]
default_target_type = "automatic"
